dataset = "GTCTATAGTGCGTCGCACCTGATGTAAGTTCTTAACGTGCTAAGGACAAGTTGGGGCACCCTGAGTCATATCAGCCATAAAGGAACCCCTACCTCGCGGGGGCTAGTTTATCCTTGCCCTACTTCTGTCCGTGATTTCACCGACACTACTATACAGTCCGTCCATGTATCAATGCGCTTGCAAAAATGGGGATACTAGTTAGCACTTGGGGGGTCAATGAGATCTTATCACTCAACTCTCTCCCGCTTGGCCAGTGGGCGTTGTTAGACCCTCAGGGGACAGCAAAGTCTCGGTTGTCCTCTTGTGCCGTGACCCTTAGGATTGGAGCCCATAGATAATATCAATGCTCCTTGGTGCGAATGCACGAGCCGTTGTCGGGGCTGCGTAAAAGGCGATCGTACTGCTGTTTATTTATAGCGGGGACAATGCTATATGACACATGAATACTCGGACAGTGACGCGCATGCAGAGCCTGTTTAATGAGGTCGGTTAGTGCACGCATAGCTAGCCGCTCCGGGTCCTCTAAAAATGCTGTTACCGATGTGTCGTTGTTTAAAAGGTTTCAGCTTTGACTATCAGAGATGGGAAATTGCGTCAGATTCCTTCGGGCGCACATTTGTTCTTGGATTTTAATCCTTTACACACGTGGACCACTCAACTGGCTCGCCGGGTCGAAGGCAGAAACAATCAAAGCTAATGTGGCCGAATAGCATGCTCACCAACCCGAGCGAACCCGAAATGAAAGAACCATTCTCGCCCATCGCCCGCGCTTAAGCCGAACTACGATAAGTTCCCTACAAGTCGCGGCTCTTTGATCAAATCGAAACCCACATCTGGAAGAGGACTGCAGATACAAGGTGAGTAAGTGCCGTGTCGGTGGATGATAAAATCACTTACACCATGGCTGGAGCGCGTAGCACTAGGTTTGTTGCTCGCAGCTCGAAGCCTCTGCTATGGTGGACTTCTCGGTTGATCTACGCATACGC"
a_counter = 0
c_counter = 0
g_counter = 0
t_counter = 0


for x in dataset:
    DNA = x

    if DNA == "A":
        a_counter = a_counter + 1
    elif DNA == "C":
        c_counter = c_counter + 1
    elif DNA == "G":
        g_counter = g_counter + 1
    else:
        t_counter = t_counter + 1

print(f"{a_counter} {c_counter} {g_counter} {t_counter}")


